# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: forge
      POSTGRES_PASSWORD: forge
  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
    environment:
      PORT: 3000
      DB_USERNAME: forge
      DB_PASSWORD: forge
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: api
    ports:
      - '3000:3000'
    depends_on:
      - db
